Ветка с логикой
Endless1ve/CardsJs pull request #6
Opened 2023-10-19 18:45 UTC by Endless1ve

2023-10-20 11:56 UTC, leka-ren requested changes
Так, есть моменты которые сразу стоит переделать:
1. Хочется чтобы попап закрывался при сабмите поста
2. Конпка почистить все не делает того что ожидается, во первых не выпадает хоть какой нибудь вопрос, даже хотя бы через алерт, точно ли я хочу все удалить, во вторых, почему так много слов еще и на англ, напиши в кнопке "Удалить все", ну и в третьих, но не супер обязательно, вынести кнопку в место, куда пользователь не тыкнет случайно, лично подробнее могу пояснить этот момент.
3. Почему когда я нажимают кнопку чистки, у меня не удаляются все карточки, а возвращается дефолтный список? Я как пользователь ожидаю какую то надпись, типа "В профиле нет картинок"

2023-10-20 13:12 UTC, Endless1ve commented
Добавлено закрытие модального окна по кнопке esc

2023-10-20 14:54 UTC, Endless1ve commented
Реализован попап для удаления всех карточек. При отсутствии карточек рендерится надпись об отсутствии карточек.

2023-10-20 16:29 UTC, Endless1ve commented
Добавлена заглушка для не загрузившихся изображений

2023-10-26 13:22 UTC, leka-ren requested changes
В общем и целом все хорошо, буквально пара косяков, поправь и все будет готово. По поводу максимальной ширины для медиа запросов, думай сам, задумка хорошая, но надо учитывать что сенсорные разрешения начинаются раньше чем предписано в стандартах фигмы(768пх). Не забывай разделять код новыми строками.

2023-10-26 13:22 UTC, leka-ren commented on js/formLogic.js
> +    if (nameInput.value.length === 0 || linkInput.value.length === 0) {
простенькая какая валидация, но в общем ок

2023-10-26 13:22 UTC, leka-ren commented on js/localStorageLogic.js
> +    const cards = Array.from(JSON.parse(localStorage.cards));
У тебя столько работы с локалом, вроде хорошо выглядит что все разделено, легко читается, но как будто бы можно какую то фабрику сделать для работы с локалом. В общем все ок, но хз, как будто я бы по другому сделала.

2023-10-26 13:22 UTC, leka-ren commented on js/popupLogic.js
> +}
Каша малаша какая то, хоть бы новыми строчками по группам дробил что ли. Читат тяжело.

2023-10-26 13:22 UTC, leka-ren commented on js/popupLogic.js
> +    yesButton.addEventListener('click', closeConfirmPopup);
Почему ты вешаешь два слушателя на клик, на одну кнопку? Сделай отдельный обработчик, на один эвент.
можно прям тут сделать addEventListener('click', (...) => {...}) типа так и вызвать тут прям че надо, а не навешивать два одинаковых слушателя на одну и ту же кнопку, только потому что надо две разные функции вызвать

2023-10-26 13:46 UTC, Endless1ve commented on js/popupLogic.js
> +}
fixed

2023-10-26 13:49 UTC, Endless1ve commented
Убрал дублирующийся слушатель событий. Добавил строчек между инструкциями для удобного чтения

2023-10-26 13:49 UTC, Endless1ve commented on js/cardLogic.js
> +    const newCard = addCard(nameInput.value, linkInput.value, id);
Мерси

2023-10-27 10:49 UTC, leka-ren approved these changes
Гуд

2023-11-13 11:29 UTC, merged